version: "3"
services: 
    api:
        build: 
            context: .
            dockerfile: ./infra/Dockerfile
        ports: 
            - "5000:5000"
        volumes:
            # Constantly (consistent strategy) sync `assets/` folder between
            # container and host
            - ".:/app:consistent"
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        environment: 
            # Pull node variables from .env file
            POSTGRES_PASSWORD: "password"
        depends_on: 
            - redis
    redis:
        image: redis